name: common_assessment_tool

services:
  backend:
    build:
      context: .
    image: backend_image:latest
    container_name: backend_container
    ports:
      - "8000:8000"
    env_file:
      - .env