name: CI/CD Pipeline

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel

      - name: Install dependencies from pyproject.toml
        run: |
          pip install .

      - name: Run Black Formatter
        run: |
          black .

      - name: Run Linter
        run: |
          pylint app tests

      - name: Run Tests
        run: |
          python -m pytest tests/

      - name: Print Test Success Message
        run: |
          echo "✓ Code checked out"
          echo "✓ Python environment set up"
          echo "✓ Dependencies installed"
          echo "✓ Linting completed"
          echo "✓ Tests executed"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t common-assessment-tool .

      - name: Run Docker Container
        run: |
          docker run -d --name backend_container --env-file .env -p 8000:8000 common-assessment-tool
          sleep 10  # Wait for container to start

      - name: Test Docker Container
        run: |
          curl http://localhost:8000/docs

      - name: Print Deploy Success Message
        run: |
          echo "Docker image built and container is running as expected!"
