name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t josephmsong/common-assessment-tool:latest .

      - name: Push Docker Image
        run: docker push josephmsong/common-assessment-tool:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop josephmsong/common-assessment-tool:latest || true
            docker rm josephmsong/common-assessment-tool:latest
            docker pull josephmsong/common-assessment-tool:latest
            docker run -d --env-file /home/ec2-user/app/.env -p 8000:8000 josephmsong/common-assessment-tool:latest
